[dependencies]
base = "0.10.2"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
itertools = "0.1.2"

[package]
name = "icrc1"
version = "0.0.1"
description = "A full implementation of the ICRC-1 fungible token standard"
repository = "https://github.com/NatLabs/icrc1"
keywords = [ "icrc1", "fungible", "token", "standard", "dfinity" ]
