name: Makefile CI

on:
  push:
    branches:
      - main
      - dev
  pull_request_target:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.1

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install mops
        run: |
          npm --yes -g i ic-mops
          mops i
          mops toolchain use moc 0.10.2

      # - name: Detect warnings
      #   run: make no-warn

      - name: Run Tests
        run: |
          make test
          make actor-test

  icrc1-ref-test:
    runs-on: ubuntu-latest

    name: ICRC-1 reference test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install mops
        run: |
          npm --yes -g i ic-mops
          mops i
          mops toolchain use moc 0.10.2

      - name: Run reference tests
        run: |
          echo "${{ secrets.IDENTITY_SSH }}" > ./identity.pem
          dfx identity import icrc-ref-test ./identity.pem --storage-mode plaintext
          dfx identity use icrc-ref-test
          dfx identity whoami
          make ref-test
